set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/rmaratos/Downloads/zed_board.xdc rfile:../../../../../../../Downloads/zed_board.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	V12	[get_ports {	OV7670_PCLK	}	]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7670_PCLK_IBUF]
